[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30
containerPort = 3000

[deploy.env]
NODE_ENV = "production"

[deploy.docker]
command = "bun run start:prod"
ports = ["3000:3000"]
